# Generated by Django 4.2.20 on 2025-03-10 06:07

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Verse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "version_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "version_abbr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "testament_abbr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "testament_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("book_name", models.CharField(blank=True, max_length=255, null=True)),
                ("book_number", models.IntegerField(blank=True, null=True)),
                ("chapter_number", models.IntegerField(blank=True, null=True)),
                ("verse_number", models.IntegerField(blank=True, null=True)),
                ("verse", models.CharField(blank=True, max_length=1024, null=True)),
                ("customId", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "verse",
            },
        ),
    ]
