# Generated by Django 4.2.20 on 2025-03-10 19:26

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("verses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verse",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
