# Generated by Django 4.2.20 on 2025-03-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verses", "0004_verse_tokens"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="verse",
            name="customId_index",
        ),
        migrations.RenameField(
            model_name="verse",
            old_name="customId",
            new_name="cid",
        ),
        migrations.AddIndex(
            model_name="verse",
            index=models.Index(fields=["cid"], name="customId_index"),
        ),
    ]
