# Generated by Django 4.2.20 on 2025-03-10 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("verses", "0005_remove_verse_customid_index_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="verse",
            name="embedding_index",
        ),
    ]
