# Generated by Django 4.2.20 on 2025-03-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verses", "0006_remove_verse_embedding_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="semantic",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="verse",
            name="cid",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="verse",
            name="topic",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
