# Generated by Django 4.2.18 on 2025-03-06 23:32

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ntopic", models.CharField(max_length=255)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("book2", models.CharField(max_length=255)),
                ("chapter2", models.CharField(max_length=255)),
            ],
        ),
    ]
