# Generated by Django 4.2.18 on 2025-03-07 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="book2",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="ntopic",
            new_name="topic",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="chapter2",
            new_name="video",
        ),
    ]
