# Generated by Django 4.2.20 on 2025-03-07 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0002_rename_book2_topic_book_rename_ntopic_topic_topic_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="topic",
            table="topic",
        ),
    ]
