# Generated by Django 4.2.20 on 2025-03-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0003_alter_topic_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="book",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="video",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
