# Generated by Django 4.2.18 on 2025-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0003_delete_tabc_delete_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("desc", models.TextField(max_length=255)),
            ],
        ),
    ]
