# Generated by Django 4.2.18 on 2025-01-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0004_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonquestions",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
