# Generated by Django 4.2.18 on 2025-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0005_alter_commonquestions_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonquestions",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("CN", "Simplified-Chinese"),
                    ("ZH", "Traditional-Chinese"),
                    ("French", "French"),
                ],
                default="ZH",
            ),
        ),
    ]
