# Generated by Django 4.2.18 on 2025-01-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0006_commonquestions_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonquestions",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("English", "English"),
                    ("CN", "Simplified-Chinese"),
                    ("ZH", "Traditional-Chinese"),
                    ("French", "French"),
                ],
                default="ZH",
                max_length=10,
                null=True,
            ),
        ),
    ]
