# Generated by Django 4.2.18 on 2025-01-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0007_alter_commonquestions_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonquestions",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
