# Generated by Django 4.2.18 on 2025-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0008_alter_commonquestions_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonquestions",
            name="date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
