# Generated by Django 4.2.18 on 2025-01-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0009_alter_commonquestions_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="commonquestions",
            name="date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
