# Generated by Django 4.2.18 on 2025-01-29 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0010_answer_rating_alter_answer_date_alter_comment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="commentn",
        ),
    ]
