# Generated by Django 4.2.18 on 2025-02-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0013_comment_question_alter_comment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonquestions",
            name="agent",
            field=models.CharField(
                choices=[("Pastor", "Pastor"), ("Priest", "Priest")],
                default="Priest",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="commonquestions",
            name="status",
            field=models.CharField(
                choices=[("asked", "asked"), ("published", "published")],
                default="asked",
                max_length=64,
            ),
        ),
    ]
